[Fix] `leo execute` on-chain option
ProvableHQ/welcome pull request #361
Opened 2024-04-26 21:23 UTC by evan-schott

Execute a leo function on-chain

2024-04-27 18:27 UTC, acoglio commented on documentation/leo/05_commands.md
> +To execute a Leo transition function on-chain. Note that the program must already have been successfully deployed.
```suggestion
To execute a Leo transition function locally, generating a zero-knowledge proof, and verifying the zero-knowledge proof on-chain. Note that the program must already have been successfully deployed.
```

2024-04-27 18:28 UTC, acoglio requested changes
I suggested a rewording, since we don't actually execute transitions on-chain like Ethereum: we execute off-chain, generate a ZK proof, and verify the ZK proof on-chain. Perhaps there's a better wording than I suggested, but it gets to the gist of it.

2024-05-07 15:21 UTC, d0cd commented
@evan-schott Does this need to be updated after the feedback from code review?

2024-05-24 13:53 UTC, acoglio approved these changes

2024-08-23 16:51 UTC, closed without merging