WIP: [Update] - API and SDK Docs
ProvableHQ/welcome pull request #389
Opened 2024-07-29 18:19 UTC by jaketarnow

This PR updates all relevant documentation for API endpoints and SDK

2024-07-29 18:51 UTC, christianwwwwwwww requested changes

2024-07-29 18:51 UTC, christianwwwwwwww commented on documentation/00_overview.md
> +- [Get Committee](./testnet/public_endpoints/14_get_committee)
append `.md` to this link

2024-07-29 18:51 UTC, christianwwwwwwww commented on documentation/00_sdk_overview.md
> +## 2. [Create-leo-App](./sdk/create-aleo-app/00_app_installation.md) - Zero Knowledge Web App Examples
"Zero-Knowledge" with hyphen

2024-07-29 18:51 UTC, christianwwwwwwww commented on documentation/testnet/getting_started/00_overview.md
> +- [Get Beacons](../public_endpoints/14_get_committee)
append `.md` to this link

2024-07-29 22:05 UTC, christianwwwwwwww approved these changes
LGTM 🤓

2024-07-31 00:20 UTC, d0cd approved these changes

2024-07-31 00:20 UTC, merged